---

- name: remove old apt cache
  shell: rm -rf /var/lib/apt/lists/*

- name: add debian strech repo
  lineinfile:
    path: /etc/apt/sources.list
    state: present
    line: "deb http://deb.debian.org/debian stretch main"

- name: add apt key for clickhouse repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C8F1E19FE0C56BD4

- name: "add apt repo for clickhouse"
  apt_repository:
    repo: deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
    state: present
    filename: clickhouse

- name: install clickhouse
  apt:
    name:
      - clickhouse-server
      - clickhouse-client
    state: latest
    update_cache: yes
    allow_unauthenticated: yes

#- name: set zero_if_notfound to yes for default mandate level
#  lineinfile:
#    path: "/etc/parsec/mswitch.conf"
#    regexp: '^zero_if_notfound: no'
#    line: 'zero_if_notfound: yes'
