---

- name: Create slurm group
  group:
    name: "{{ SLURM_USER.group }}"
    gid: "{{ SLURM_USER.gid }}"
    system: "{{ SLURM_USER.system | default('yes')}}"

- name: Create slurm user
  user:
    name: "{{ SLURM_USER.name }}"
    comment: "{{ SLURM_USER.comment | default(omit) }}"
    uid: "{{ SLURM_USER.uid }}"
    group: "{{ SLURM_USER.group}}"
    groups: "{{ SLURM_USER.groups | default(omit) }}"
    home: "{{ SLURM_USER.home }}"
    shell: "{{ SLURM_USER.shell }}"
    system: "{{SLURM_USER.system | default('yes')}}"

