image: golang:latest

variables:
  REPO_NAME: gitlab.at.ispras.ru/openstack_bigdata_tools/spark-openstack

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$(dirname $REPO_NAME)
  - go get -u google.golang.org/grpc
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/hashicorp/vault/api
  - go get -u gopkg.in/yaml.v2
  - go get github.com/julienschmidt/httprouter
  - go get -u gopkg.in/couchbase/gocb.v1
  - go get github.com/golang/mock/mockgen

stages:
  - test
  - deploy


runtests:
  stage: test
  script:
    - pwd
    - go test ./src/handlers/ -cover


deployapp:
  stage: deploy
  script:
    - echo "Deploying the code"