###############################
## Configure yours variables ##
###############################

os_key_name: OS_KEY_NAME
virtual_network: NETWORK
os_image: OS_IMAGE
floating_ip_pool: IP_POOL
flavor: FLAVOR
os_version: VERSION #stein or liberty