---

- name: remove old apt cache
  shell: rm -rf /var/lib/apt/lists/*

- name: add apt key for couchdb repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0EE62FB37A00258D

- name: add apt repo for couchdb
  apt_repository:
    repo: deb https://apache.jfrog.io/artifactory/couchdb-deb/ {{ansible_lsb.codename}} main
    state: present
    filename: couchdb

- name: install couchdb
  apt:
    name:
      - couchdb
    state: latest
    update_cache: yes
    allow_unauthenticated: yes
