---

- name: Install necessary packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - curl
    - python-software-properties

- name: Add nodejs LTS repo
  become: yes
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - "

- name: copy jupyterhub sudospawner sudo config
  copy: src=sudo_jupyter dest=/etc/sudoers.d/jupyter mode=0440 owner=root group=root
  become: yes
  tags:
  - install
  - jupyterhub_install

- debug: var=python_version
- block:
  - name: install packages
    become: yes
    apt: name={{ item }} state=present
    with_items:
      - nodejs

  - become: yes
    npm:
      global: true
      name: configurable-http-proxy

  - name: install pip packages
    become: yes
    pip: name={{ item }} state=present executable=pip{{ python_version }}
    with_items:
      - jupyterhub
      - sudospawner
      - jupyterhub-dummyauthenticator

  - copy: src=jupyterhub_config.py dest={{ jupyterhub_workingdir }}
  tags:
  - install
  - jupyterhub_install

- include: service_jupyterhub.yml
  become: yes
  become_user: root
  tags:
  - install
  - jupyterhub_install