---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Register master facts
      os_server_facts:
        filters:
          metadata:
            group: "{{ cluster_name }}_master"
      no_log: True
    - debug: msg="{{ openstack_servers[0].interface_ip }}"
