---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "apt-transport-https"
    state: latest
    update_cache: yes

- name: Add docker repo key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install docker
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes
