---

- name: get spark_use_yarn
  shell: grep "{{active_master}}" "/usr/local/hadoop/etc/hadoop/yarn-site.xml"
  ignore_errors: True
  register: use_yarn_cmd_res
- set_fact: spark_use_yarn={{use_yarn_cmd_res.rc == 0}}
- debug: msg="spark_use_yarn={{spark_use_yarn}}"
