#Defaults for slurmd

SLURMD_SERVICE_NAME: slurmd

#packages to install
SLURM_PACKAGES: 
  slurmd: [slurmd]
#parameters for config file
ACCOUNTING_STORAGE_HOST: "{{ cluster_name }}-storage"
CLUSTER_NAME: "{{ cluster_name }}"
SLURM_MASTER: "{{ cluster_name }}-master"

OS_IMAGE: "{{ ansible_facts ['distribution_version']  == '21.04' }}"

SLURM_PATH_TO_PID_FILE: "{{'/var/run/slurm' if OS_IMAGE else '/var/run/slurm-llnl'}}"
SLURM_PATH_TO_LOG_FILE: "{{'/var/log/slurm' if OS_IMAGE else '/var/log/slurm-llnl'}}"
SLURM_CONFIG_DIR: "{{'/etc/slurm' if OS_IMAGE else '/etc/slurm-llnl'}}"


STATE_SAVE_LOCATION_MASTER: /var/spool/slurmctld
STATE_SAVE_LOCATION_SLAVE: /var/spool/slurmd
Task_Plugin_Param: None

#parameters for database
DIR_FOR_KEY: ./files