---

- name: Install Slurm DB packages
  package:
    name: slurmdbd
    state: latest

#TODO: parameters + dir for user 
- name: Install slurm.conf
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444

#TODO: parameters + dir for user 
- name: Install slurmdbd.conf
  template:
    src: templates/slurm/slurmdbd.conf.j2
    dest: "{{ SLURM_CONFIG_DIR }}/slurmdbd.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - reload slurmdbd


