---

- name: Install Slurm DB packages
  package:
    name: slurmdbd
    state: latest
 
- name: Install slurm.conf
  template:
    src: "{{ slurm_config_dir }}"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444

- name: Install slurmdbd.conf
  template:
    src: templates/slurm/slurmdbd.conf.j2
    dest: "{{ SLURM_CONFIG_DIR }}/slurmdbd.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - reload slurmdbd


