---
#needs vars from spark_common

- name: start hadoop dfs
  command: "/usr/local/hadoop/sbin/start-dfs.sh"
  tags:
    - start


- name: start hadoop yarn
  command: "/usr/local/hadoop/sbin/start-yarn.sh"
  when: spark_use_yarn
  tags:
    - start

- name: start spark master
  shell: SPARK_MASTER_IP="{{ cluster_name }}-master" /opt/spark/sbin/start-master.sh
  when: not spark_use_yarn
  tags:
    - start

- name: start the slaves
  shell: "/opt/spark/sbin/start-slaves.sh"
  when: not spark_use_yarn
  tags:
    - start
