---

- name: Install nfs-client and update cache
  become: true
  apt:
    name: nfs-common
    state: latest
    update_cache: yes

- name: Incclude tasks 
  include: add_share.yml
  
- name: mount
  become: true 
  shell: mount -a