OS_IMAGE: "{{ slurm_os_image == 'ubuntu21.04' }}"


#defaults to create directories
OS_IMAGE: "{{ slurm_os_image == 'ubuntu21.04' }}"

SLURM_PATH_TO_PID_FILE: "{{'/var/run/slurm' if OS_IMAGE else '/var/run/slurm-llnl'}}"
SLURM_PATH_TO_LOG_FILE: "{{'/var/log/slurm' if OS_IMAGE else '/var/log/slurm-llnl'}}"
SLURM_CONFIG_DIR: "{{'/etc/slurm' if OS_IMAGE else '/etc/slurm-llnl'}}"

ACCOUNTING_STORAGE_HOST: "{{ cluster_name }}-storage"
CLUSTER_NAME: "{{ cluster_name }}"
SLURM_MASTER: "{{ cluster_name }}-master"

STATE_SAVE_LOCATION_MASTER: /var/spool/slurmctld
STATE_SAVE_LOCATION_SLAVE: /var/spool/slurmd

#defaults for slurm user 
SLURM_USER:
  name: slurm
  comment: "Slurm Workload Manager"
  uid: 888
  gid: 888
  home: /var/lib/slurm
  shell: /usr/sbin/nologin
  group: slurm