---

- name: restart munge
  service:
    name: munge
    state: restarted

- name: reload slurmctld
  systemd:
    name: slurmctld
    state: reloaded
 
- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
