---

- name: Include tasks for installing OpenMpi
  include_tasks: open_mpi.yml
  when: slurm_use_open_mpi is defined and slurm_use_open_mpi

- name: Include tasks to install and configure Open FOAM
  include_tasks: open_foam.yml
  when: slurm_use_open_foam is defined and slurm_use_open_foam

- name: Install slurm-wlm package
  become: true
  apt:
    update_cache: yes
    name: slurm-wlm
    state: latest
  
- name: Include tasks for time synchronization
  include_tasks: ntp.yml
  
- name: Include tasks for creation directories
  include: directory.yml

- name: Include jwt auth instalation tasks 
  include_tasks: jwt.yml
  when: slurm_use_rest is defined and slurm_use_rest

- name: Include http_parser instalation tasks
  include_tasks: http_parser.yml
  when: slurm_use_rest is defined and slurm_use_rest

- name: Include controller installation tasks
  include_tasks: controller.yml

- name: Include task for configuring munge 
  include_tasks: munge.yml

- name: Ensure slurmctld is enabled and running
  become: true
  systemd:
    name: slurmctld
    enabled: yes
    state: started
