---

- name: Check munge dir
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory
  
- name: Install munge key
  become: true
  copy:
    src: "{{ DIR_FOR_KEY }}/munge.key"
    dest: /etc/munge/munge.key
    force: yes
    owner: munge
    group: munge
    mode: 0400
  notify: restart munge
  when: slurm_use_db is defined and slurm_use_db

- name: Ensure munge is enabled and running
  become: true
  systemd:
    name: munge
    enabled: yes
    state: started

- name: Retrieve key for munge cluster
  become: true 
  fetch:
    src: /etc/munge/munge.key
    dest: "{{ DIR_FOR_KEY }}/munge.key"
    flat: yes
  notify: restart munge
  when: slurm_use_db is defined and not slurm_use_db
