---
- name: Include tasks for time synchronization
  include_tasks: ntp.yml

- name: Change parameters of limits.conf for MPI
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: memlock
    value: unlimited 
  loop: 
    - soft
    - hard  
 
#TODO: test it  
- name: Install slurm-wlm and pam_slurm packages
  apt:
    update_cache: yes
    name: 
      - slurm-wlm
      - libpam-slurm
    state: latest

- name: Configure ssh access restrictions
  lineinfile: 
    path: /etc/pam.d/sshd
    line: account required pam_slurm_adopt.so

- name: Include tasks for creation directoriees
  include: directory.yml

- name: Include execution host installation tasks
  include_tasks: slave.yml

- name: Include task for configuring munge 
  include_tasks: munge.yml

- name: Ensure slurmd is enabled and running
  systemd:
    name: slurmd
    enabled: yes
    state: started
