---

- name: Check munge dir
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Install munge key
  copy:
    src: "{{ DIR_TO_INSTALL_MUNGE_KEY }}/munge.key"
    dest: /etc/munge/munge.key
    force: yes
    owner: munge
    group: munge
    mode: 0400
  notify: restart munge

- name: Ensure Munge is enabled and running
  service:
    name: munge
    enabled: yes
    state: started

- name: Remove munge key
  file: 
    path: "{{ DIR_TO_INSTALL_MUNGE_KEY }}/munge.key"
    state: absent
