---

- name: Install Slurm execution host packages
  package:
    name: slurmd
    state: latest

- name: Create slurm spool directory
  file:
    path: "{{ STATE_SAVE_LOCATION_SLAVE }}"
    owner: root
    group: root
    mode: 0744
    state: directory
  notify:
    - reload slurmd

- name: Install slurm.conf
  become: true
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmd

- name: Install cgroup.conf
  template:
    src: "templates/slurm/cgroup.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/cgroup.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - restart slurmd
    

