#Defaults for slurmctld

SLURMCTLD_SERVICE_NAME: slurmctld

#packages to install
SLURM_PACKAGES: 
  client:  [slurm-client, slurm-wlm-doc]
  slurmctld: [slurm-wlm]
#parameters for config file
ACCOUNTING_STORAGE_HOST: "{{ cluster_name }}-storage"
CLUSTER_NAME: "{{ cluster_name }}"
SLURM_MASTER: "{{ cluster_name }}-master"
SLURM_PATH_TO_PID_FILE_MASTER: /var/run/slurm-llnl
SLURM_PATH_TO_LOG_FILE_MASTER: /var/log/slurm-llnl
SLURM_PATH_TO_LOG_FILE_SLAVE: /var/log/slurm-llnl
SLURM_PATH_TO_PID_FILE_SLAVE: /var/run/slurm-llnl
STATE_SAVE_LOCATION_MASTER: /var/spool/slurmctld
STATE_SAVE_LOCATION_SLAVE: /var/spool/slurmd
SLURM_SLAVES: "{{ cluster_name }}-slaves"
#parameters for munge
DIR_TO_INSTALL_MUNGE_KEY: ./files
SLURM_CONFIG_DIR: /etc/slurm-llnl
#defaults for user 
SLURM_USER:
  name: slurm
  comment: "Slurm Workload Manager"
  uid: 888
  gid: 888
  home: /var/lib/slurm
  shell: /usr/sbin/nologin
  group: slurm
