---
- hosts: all
  vars:
    web_user: "www-data"
  tasks:
    - name: Remove the user "{{item.pos_name}}"
      user:
        name: "{{item.pos_name}}"
        state: absent
        remove: yes
      with_items: "{{ user_list }}"

    - name: Remove directoy
      file:
        path: /external_data/{{ item.pos_name}}/
        state: absent
      with_items: "{{ user_list }}"

    - name: Remove Nexcloud user
      become_user: "{{ web_user }}"
      become_flags: "{{ ansible_become_flags | default(omit) }}"
      become: yes
      shell: php occ user:delete "keycloack-{{ item.uuid }}"
      args:
        chdir: /var/www/html
      environment:
        OC_PASS: "{{ item.uuid }}"
      with_items: "{{ user_list }}"

