---
- hosts: all
  vars:
    web_user: "www-data"
  tasks:
    - name: Add groups
      group:
        name: "{{ item.pos_group }}"
        gid: "{{ item.pos_gid }}"
        state: present
      with_items: "{{ user_list }}"
      ignore_errors: yes

    - name: Add the user "{{ item.pos_name }}" with uid "{{ item.pos_uid }}" and a primary gid "{{ item.pos_gid }}"
      user:
        name: "{{ item.pos_name }}"
        comment: "{{ item.uuid }}"
        uid: "{{ item.pos_uid }}"
        shell: "/bin/bash"
        groups: "{{ item.pos_group }}"
        home:  "/external_data/{{ item.pos_name }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: "/external_data/{{ item.pos_name }}/.ssh/id_rsa"
      with_items: "{{ user_list }}"

    - shell: mkdir  /tmp/ssh/
      ignore_errors: yes

    - name: Genterate authorized_keys for users
      shell: su -c "cat /external_data/{{ item.pos_name }}/.ssh/id_rsa.pub >> /external_data/{{ item.pos_name }}/.ssh/authorized_keys"
      with_items: "{{ user_list }}"

    - shell: chown -R "{{ item.pos_name }}:{{ item.pos_group }}"  /external_data/{{ item.pos_name }}/
      with_items: "{{ user_list }}"


    - shell: openssl genrsa -out /tmp/ssh/rsa_{{ item.pos_name }} 1024
      with_items: "{{ user_list }}"

    - shell: ssh-keygen -y -f /tmp/ssh/rsa_{{ item.pos_name }} >>/tmp/ssh/rsa_{{ item.pos_name }}.pub
      with_items: "{{ user_list }}"

    - shell: cat /tmp/ssh/rsa_{{ item.pos_name }}.pub >> /external_data/{{ item.pos_name }}/.ssh/authorized_keys
      with_items: "{{ user_list }}"

    - name: Add group to Nextcloud
      become_user: "{{ web_user }}"
      become_flags: "{{ ansible_become_flags | default(omit) }}"
      become: yes
      shell: php occ group:add "{{ item.pos_group }}"
      args:
        chdir: /var/www/html
      ignore_errors: yes
      with_items: "{{ user_list }}"

    - name: Add user to Nexcloud
      become_user: "{{ web_user }}"
      become_flags: "{{ ansible_become_flags | default(omit) }}"
      become: yes
      shell: php occ user:add --display-name "{{ item.pos_name }}" --group  "{item.pos_group}" "keycloack-{{ item.uuid }}" --password-from-env
      args:
        chdir: /var/www/html
      environment:
        OC_PASS: "{{ item.uuid }}"
      with_items: "{{ user_list }}"

    - shell: chown -R "{{ web_user }}" /tmp/ssh/

    - name: Add user external storage sftp
      become_user: "{{ web_user }}"
      become_flags: "{{ ansible_become_flags | default(omit) }}"
      become: yes
      shell: php occ files_external:create --user  "keycloack-{{ item.uuid }}" --config user="{{ item.pos_name }}" --config host=127.0.0.1 --config public_key="$(cat /tmp/ssh/rsa_{{ item.pos_name }}.pub)" --config  private_key="$(cat /tmp/ssh/rsa_{{ item.pos_name }})" --config root="/external_data/{{ item.pos_name }}" "HOME"  sftp  "publickey::rsa"
      register: files_external_out
      args:
        chdir: /var/www/html
      with_items: "{{ user_list }}"

    - shell: "rm -rf /tmp/ssh/*"