--- 

- name: Install nfs-server and update cache
  apt:
    name: nfs-kernel-server
    state: latest
    update_cache: yes

- name: Include tasks for edding configuration file export 
  include: nfs-add-export.yml
  
#- include: fdisk.yml
#  tags: fdisk

- name: Restart nfs-server
  service:
    name: nfs-kernel-server
    state: restarted