---

- name: Install Slurm controller packages
  package:
    name: slurmctld
    state: latest

- name: Create slurm state directory
  file:
    path: "{{ STATE_SAVE_LOCATION_MASTER }}"
    owner: root
    group: root
    mode: 0744
    state: directory
  notify:
    - reload slurmctld

- name: Install slurm.conf
  become: true
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmctld

- name: Install cgroup.conf
  template:
    src: "templates/slurm/cgroup.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/cgroup.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmctld

