---

#TODO: parameters + dir for user
- name: Install slurm.conf
  become: true
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmctld

#TODO: dir for user
- name: Install cgroup.conf
  become: true
  template:
    src: "templates/slurm/cgroup.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/cgroup.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmctld

