---

- name: Adding key for the repository to enable package signatures to be verified.
  become: true 
  apt_key:
    url: https://dl.openfoam.com/pubkey.gpg

- name: Adding dl.openfoam.org to the list of software repositories
  become: true 
  apt_repository:
    repo:  deb [arch=amd64] https://dl.openfoam.com/repos/deb hirsute main

- name: Install packages for Open FOAM
  become: true 
  apt: 
    name: openfoam2012-dev
    update_cache: yes

- name: Configure ~/.bashrc
  become: true 
  lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'source /usr/lib/openfoam/openfoam2012/etc/bashrc'
    insertafter: EOF

- name: Source ~/.bashrc  
  shell: . ~/.bashrc