---

- name: restart munge
  systemd:
    name: munge
    state: restarted

- name: reload slurmd
  systemd:
    name: slurmd
    state: reloaded

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted


