---

#TODO: Parameters + dir for user
- name: Install slurm.conf
  become: true
  template:
    src: "{{ slurm_config_dir }}"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmd

#TODO: Parameters + dir for user
- name: Install cgroup.conf
  become: true
  template:
    src: "{{ slurm_cgroup_config_dir }}"
    dest: "{{ SLURM_CONFIG_DIR }}/cgroup.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmd
    

