---

#TODO: Parameters + dir for user
- name: Install slurm.conf
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmd

#TODO: Parameters + dir for user
- name: Install cgroup.conf
  template:
    src: "templates/slurm/cgroup.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/cgroup.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - reload slurmd
    

