---

- name: Clone repository for jwt 
  shell: git clone --depth 1 --single-branch -b v1.12.0 https://github.com/benmcollins/libjwt.git libjwt

- name: Installation packages to configure
  become: yes
  apt:
    name: 
      - autoconf
      - libtool
      - pkg-config
      - libssl-dev
      - libjansson-dev
      - make
    update_cache: yes

- name: Configure 
  command: "{{ item }}"
  loop: 
    - autoreconf --force --install
    - ./configure --prefix=/usr/local
    - make -j
  args:
    chdir: libjwt

- name: Run 'install' target as root
  make: 
    chdir: libjwt
    target: install
  become: yes
  
- name: Generate the jwt_hs256.key
  shell: sudo dd if=/dev/random of={{SLURM_CONFIG_DIR}}/jwt_hs256.key bs=32 count=1