---

- name: Clone repository for jwt 
  shell: git clone --depth 1 --single-branch -b v1.12.0 https://github.com/benmcollins/libjwt.git libjwt

- name: Upgrade all packages 
  apt:
    upgrade: full

- name: Installation packages to configure
  apt:
    name: 
      - autoconf
      - libtool
      - pkg-config
      - libssl-dev
      - libjansson-dev
      - make 

- name: Configure 
  command: "{{ item }}"
  loop: 
    - autoreconf --force --install
    - ./configure --prefix=/usr/local
    - make -j
  args:
    chdir: libjwt

- name: Run 'install' target as root
  make: 
    chdir: libjwt
    target: install
  
- name: Generate the jwt_hs256.key
  become: yes
  shell: dd if=/dev/random of={{SLURM_CONFIG_DIR}}/jwt_hs256.key bs=32 count=1

- name: Save jwt_hs256.key
  fetch:
    src: /etc/slurm/jwt_hs256.key
    dest: "{{ DIR_FOR_KEY }}/jwt_hs256.key"
    flat: yes
