---

- name: Check munge dir
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Ensure Munge is enabled and running
  service:
    name: munge
    enabled: yes
    state: started

- name: Retrieve key for munge cluster
  fetch:
    src: /etc/munge/munge.key
    dest: "{{ DIR_FOR_KEY }}/munge.key"
    flat: yes
  notify: restart munge

