---

- name: Install Slurm DB packages
  become: yes
  package:
    name: slurmdbd
    state: latest

- name: Install slurm.conf
  become: true
  template:
    src: "templates/slurm/slurm.conf.j2"
    dest: "{{ SLURM_CONFIG_DIR }}/slurm.conf"
    owner: root
    group: root
    mode: 0444

- name: Install slurmdbd.conf
  become: yes 
  template:
    src: templates/slurm/slurmdbd.conf.j2
    dest: "{{ SLURM_CONFIG_DIR }}/slurmdbd.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - reload slurmdbd


