---
- name: Install packages for MariaDB
  apt: 
    update_cache: yes
    name: "{{item}}"
    state: present 
  loop: 
    - mariadb-server
    - python3-pip
  
- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Ensure InnoDB parameters are large enough for Slurmdbd
  blockinfile:
    path: '/etc/mysql/my.cnf'
    state: present
    insertafter: EOF
    content: |
      # See https://wiki.fysik.dtu.dk/niflheim/Slurm_database#id5
      [mysqld]
      innodb_buffer_pool_size=1G
      innodb_log_file_size=64M
      innodb_lock_wait_timeout=900
  when: deploy_slurm is defined and deploy_slurm

- name: Change configuration file for mariaDB
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address={{active_master_ip}} '
  when: deploy_slurm is defined and deploy_slurm

- name: Ensure MariaDB daemon is started
  systemd:
    name: 'mariadb'
    state: started
    enabled: yes

- name: Create DB 
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mariadb
    state: present

- name: Print parameters of db
  debug:
    var: "{{ item }}"
  loop: 
      - "{{ db_user }}"
      - "{{ db_password }}"

- name: Create DB user
  mysql_user:
    login_user: root
    login_password: ' '
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: 'mariadb.*:ALL'
    state: present
